# Generated by Django 2.1.3 on 2020-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatm',
            name='hezb',
            field=models.CharField(max_length=100, verbose_name='حزب'),
        ),
        migrations.AlterField(
            model_name='khatm',
            name='joz',
            field=models.CharField(max_length=100, verbose_name='جز'),
        ),
    ]
